export { adminService } from './services/admin.service';
export {
  useAdminOrders,
  useUpdateOrderStatus,
  useAdminInventory,
  useUpdateStock,
  useAdminUsers,
  useUpdateUserRole,
  useAdminProducts,
  useCreateProduct,
  useUpdateProduct,
  useDeleteProduct,
  useAddProductImage,
  useDeleteProductImage,
  useAdminProductById,
  useAddVariant,
  useDeleteVariant,
  useAdminCategories,
  useCreateCategory,
  useUpdateCategory,
  useDeleteCategory,
  useAdminCoupons,
  useCreateCoupon,
  useToggleCoupon,
  useAdminPromotions,
  useAdminPromotionById,
  useCreatePromotion,
  useUpdatePromotion,
  useTogglePromotion,
  useDeletePromotion,
} from './hooks/useAdmin';
export type {
  AdminOrder,
  AdminInventoryVariant,
  AdminUser,
  PaginatedResponse,
  AdminOrderQuery,
  AdminProduct,
  AdminProductVariant,
  AdminProductsQuery,
  CreateProductPayload,
  UpdateProductPayload,
  CreateVariantPayload,
  AddProductImagePayload,
  AdminProductImage,
  AdminCategory,
  CreateCategoryPayload,
  UpdateCategoryPayload,
  AdminCoupon,
  CreateCouponPayload,
  DiscountType,
  AdminPromotion,
  CreatePromotionPayload,
  UpdatePromotionPayload,
  PromotionListQuery,
  PromotionScope,
} from './types/admin.types';
