export { adminService } from './services/admin.service';
export {
  useAdminOrders,
  useUpdateOrderStatus,
  useAdminInventory,
  useUpdateStock,
  useAdminUsers,
  useUpdateUserRole,
  useAdminProducts,
  useCreateProduct,
  useUpdateProduct,
  useDeleteProduct,
  useAddProductImage,
  useDeleteProductImage,
  useAddVariant,
  useAdminCategories,
  useCreateCategory,
  useUpdateCategory,
  useDeleteCategory,
  useAdminCoupons,
  useCreateCoupon,
  useToggleCoupon,
} from './hooks/useAdmin';
export type {
  AdminOrder,
  AdminInventoryVariant,
  AdminUser,
  PaginatedResponse,
  AdminOrderQuery,
  AdminProduct,
  AdminProductVariant,
  AdminProductsQuery,
  CreateProductPayload,
  UpdateProductPayload,
  CreateVariantPayload,
  AddProductImagePayload,
  AdminProductImage,
  AdminCategory,
  CreateCategoryPayload,
  UpdateCategoryPayload,
  AdminCoupon,
  CreateCouponPayload,
  DiscountType,
} from './types/admin.types';
